### ISSUE TITLE
Feature request: double the softness range.

### ISSUE THREAD

**Issue by magnetophon** [223230/22-CLIP#13]
Thanks for this great plugin!

I was playing with a faust port of the algo, and noticed that maximum softness still has the bottom half of the curve linear.
I doubled the softness value, and now the algo can go "fully soft" if that makes sense.
It's a very interesting sound; for certain input sounds and parameter settings, it actually sounds much cleaner still than the current max softness.

**Comment by 223230** [comment]
That sounds neat! If that already works for you locally, could you make a PR?

**Comment by 223230** [comment]
Actually, I just checked and if you used the py notebook version of the algorithm, you may have gotten a slightly different result. The rust version of the algorithm *should* be able to make the entire transfer curve go non-linear.

![50% softness](https://github.com/223230/22-CLIP/assets/68156346/85a7ded2-3323-49bc-9952-3d8cd8384f9b)

![100% softness](https://github.com/223230/22-CLIP/assets/68156346/a2ef2683-d9b6-49ff-8f1b-7219cf5f30f8)

**Comment by 223230** [comment]
I see! And no worries about the noise :D Yeah, the maxed out portion in the signal at a threshold of <0db is actually intentional. The size of the sinusoidal transitioning part of the transfer function is supposed to be proportional to the threshold, i.e. if the softness is at 100% and the threshold is at -6db - or 50% in amplitude - then the sinusoid starts linearly at 0 and reaches its peak at 50% output volume (not 50% input volume). Then, everything past the peak has to get hard clipped. If you play around with the Plugin, you'll notice that this is very similar to a compressor's "knee" (given a 1:∞ ratio, i.e. limiting). You'll find this type of setup in other clippers, like GVST's GClip. In the GUI code, I'm calling that sinusoidal part the "non-linearity area" but I'm sure there's more professional terminology for it.

Because of this, the example of 0db pre-gain, -6db threshold and 200% softness that you provided is equivalent to setting -6db pre-gain, -6db threshold, and then applying just 100% softness. And that type of "fully soft" clipping obviously *is* already possible with the current DSP :) I can't really see why you'd need a higher soft clipping range then, as the existing parameters can already achieve this. In general, I think a sinusoidal approach like the one in this clipper would be rather ill-equipped for a "fully" soft algorithm, i.e. a clipping algorithm which never maxes out, as a sine will always reach its maximum at 90° phase. You'd be better served by something like a hyperbolic tangent algorithm (which only approaches, but never reaches 1) for the transfer function.

**Comment by magnetophon** [comment]
Thanks for the insightfull response, that all makes sense.
This thread has got me experimenting some more, and I came up with 2 variations on a new algo.
I'll open a new issue for them.
