### ISSUE TITLE
Discontinuity at transition from lin to nonlin

### ISSUE THREAD

**Issue by magnetophon** [223230/22-CLIP#14]
I looked at your algorithm in desmos, saw some issues and came up with alternatives.

The first issue is a discontinuity in the derivative.
You can see the issue [in this graph](https://www.desmos.com/calculator/lykcjg5k3s).
The functions marked with 22 are your algorithms.
The ``d`` functions are the derivatives.
``s`` is the softness.

As you can see, your version has a discontinuity in the derivative, and mine doesn't.
This should provide a smoother sound.
The downsides of my version are:
- The derivative does not always fully end at 0, so there is a discontinuity in the derivative at the transition to the flat top.
  This is a much smaller discontinuity than in the original algorithm though.
- The gain of the linear part changes ever so slightly when changing the softness.

I would also like to request a different scaling of the curve, so the point at wich the input value reaches the flat top does not depend on the softness.
[Here is a demo.](https://www.desmos.com/calculator/45pem8gqya)
With this algorithm, the plugin will be more similar to a limiter with 0 attack and release time.
That way, it can be used as a mastering clipper.
This could ether be a switch between the unscaled and scaled algorithm or just hardcoding the scaled one.

On a related note, I think softness should be renamed knee, and be scaled in dB.

**Comment by 223230** [comment]
Oh wow, that discontinuity was a total oversight on my end! Thanks for figuring it out!! I actually just experimented with your demo in desmos and I found that the discontinuity also disappears if you change my algorithm by multiplying the amplitude of the sine by $\frac 3 \pi$, meaning you go from this

$1-s + \sin(\frac{\pi}{2k}\cdot(x-1+k)-\frac{\pi}{6})\cdot s)$

to this

$1-s + \sin(\frac{\pi}{2k}\cdot(x-1+k)-\frac{\pi}{6})\cdot\frac{3}{\pi} s)$

By doing this, the derivative starts at 1 and ends at 0 and the transfer function is continuous - which addresses the two downsides you brought up. My maths may be a bit borked though, I'll check back tomorrow after I get some sleep. 

> On a related note, I think softness should be renamed knee, and be scaled in dB.

I can see that, I think I mainly liked the idea of softness being a percentage value because [a certain other soft clipper I really like](https://www.gvst.co.uk/gclip.htm) also does it that way. I'm open to either, really. Maybe changing it to dB and calling it "knee" could make for a nice analog to compressors, as the transfer curve is already parameterized in kind of a similar fashion to a compressor.

> I would also like to request a different scaling of the curve, so the point at wich the input value reaches the flat top does not depend on the softness.

That algorithm could be toggled through some sort of entry in the settings page (?) later down the line, for sure. But I'm against hard-coding it in as the only option. While I'm not entirely opposed to the idea, I'd just not like to have it be the default.

What I don't like about it is that it means tweaking the knee/softness would lead to a louder/quieter sound while in the current algorithm it would just lead to different harmonic content around the threshold. In a mixing context, I'd prefer the latter because otherwise, an effective "pre-gain" would be applied that makes this plug-in sound less transparent, and - to me - more like a saturation effect than a transparent, clean clipper. Consider a compressor like the FabFilter Pro-C2 or other clipping plug-ins like the aforementioned GClip for reference - their  transfer function's linear portion isn't affected by the knee's softness at all. Rather, the knee param just changes how the transfer function behaves around its "bend".

**Comment by 223230** [comment]
Alright, I've fiddled around with my updated continuous transfer curve a little more and this is what I came up with:

https://www.desmos.com/calculator/ekaumejitx

It's a bit more simplified. Also, I made the nonlinear portion extend from $1-s$ to $1+s(\frac{\pi}{2}-1)$, so now it stops at $\frac \pi 2$ when the softness is maxed out. Don't ask me why, but the curve used to stop at 1.5, which doesn't make much sense for a sinusoidal knee - I've got no idea how that came to be. I'll blame it on me being a 1st year CS student lol.

**Comment by magnetophon** [comment]
That curve looks perfect!
How did you come up with it?
Was it mostly fiddling around with desmos, or did you derive it somehow?

**Comment by 223230** [comment]
> That curve looks perfect!

Thanks! I think I could implement it in the Rust code as well, as I already cooked up some proof of concept Rust code yesterday to implement something like this function :) If you'd sign off on that as well, I could start work on that.

> How did you come up with it?

I don't know if I'm as good of a math communicator as I am a computer science communicator, but here goes nothing lol.

The original issue you found was that the first-order derivative is >1 at the start of the knee - which is where that discontinuity came from since the transfer function is linear before that knee. The only explanation why that the first order derivative can start at >1 is if the sine is "stretched" in some way, as normally, $\frac{d}{dx}sin(0)=1$.

So I maxed out the softness, making the transfer function just the knee with no linear part before it. If we had an un-stretched sine, the knee should now go from $x=0$ to $x=\frac \pi 2$, i.e. the knee part should just be a straight up quarter period of a sine wave. But instead, the knee went from $x=0$ to $x=1.5$. A quarter period of a sine wave is supposed to be $\frac \pi 2$, so I figured that the sine function must have gotten weirdly stretched (easy to overlook, since $1.5 \approx \frac \pi 2$). As mentioned before, a stretching of the sine would be what caused that discontinuity in the slope of the transfer curve.

Then, I just made the appropriate changes to the original transfer function, but that made it look kind of convoluted, so I just started from scratch and took the time to simplify it - which is also why I'm now using a cosine.

**Comment by magnetophon** [comment]
> I think I could implement it in the Rust code as well, as I already cooked up some proof of concept Rust code yesterday to implement something like this function :) If you'd sign off on that as well, I could start work on that.

I'm not following you.
Why would it be problematic to implement in rust?
I'm a rust noob, so maybe I'm missing something very obvious here.
What do you mean by me signing off on it?

Thanks for explaining your thought process.
While trying to understand why you ended up with a ``cos`` instead of a ``sin``, I stumbled upon [an even simpler version of the same curve](https://www.desmos.com/calculator/jlghmnocbk).

**Comment by 223230** [comment]
> Why would it be problematic to implement in rust?
> What do you mean by me signing off on it?

Sorry, there might be a language barrier here. English isn't my first language :sweat_smile:

I meant that I already have a working Rust version of this new algorithm I've come up with, and therefore I could easily adapt the current plug-in code to use the new algorithm. I was just asking if you're also fine with me doing that, or if you've got any concerns with the algorithm as it stands.

> While trying to understand why you ended up with a cos instead of a sin, I stumbled upon [an even simpler version of the same curve](https://www.desmos.com/calculator/jlghmnocbk).

Thanks! I'll use that one instead :)

**Comment by magnetophon** [comment]
> Thanks! I'll use that one instead :)

Thank *you*!

I hereby officially sign of on that.  :grin:
